name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]

body:
  - type: markdown
    attributes:
      value: "Thanks for suggesting an idea! Please describe what you'd like to see."

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like?
      placeholder: "I'd like to add..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: "Currently, players can't..."

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: "The feature could..."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there other ways to do this?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: This hasn't been suggested before
        - label: This is technically feasible